spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://212.129.142.221:3306/my_miaosha0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: my-sql!@#pass-for-2019
  redis:
    host: 212.129.142.221
    port: 6379
    password: my-redis!-pass#%for--2019
server:
  port: 8090
mybatis:
  type-aliases-package: com.dail.miaosha.model
  mapper-locations: classpath*:mappers/*.xml
